# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/meiga/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/meiga/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /opt/meiga/build && $(CMAKE_COMMAND) -E cmake_progress_start /opt/meiga/build/CMakeFiles /opt/meiga/build/Applications/G4HodoscopeSimulator//CMakeFiles/progress.marks
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Applications/G4HodoscopeSimulator/all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/meiga/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Applications/G4HodoscopeSimulator/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Applications/G4HodoscopeSimulator/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Applications/G4HodoscopeSimulator/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /opt/meiga/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/rule:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/rule
.PHONY : Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/rule

# Convenience name for target.
G4HodoscopeSimulator: Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/rule
.PHONY : G4HodoscopeSimulator

# fast build rule for target.
G4HodoscopeSimulator/fast:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build
.PHONY : G4HodoscopeSimulator/fast

ExtraPhysics.o: ExtraPhysics.cc.o
.PHONY : ExtraPhysics.o

# target to build an object file
ExtraPhysics.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/ExtraPhysics.cc.o
.PHONY : ExtraPhysics.cc.o

ExtraPhysics.i: ExtraPhysics.cc.i
.PHONY : ExtraPhysics.i

# target to preprocess a source file
ExtraPhysics.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/ExtraPhysics.cc.i
.PHONY : ExtraPhysics.cc.i

ExtraPhysics.s: ExtraPhysics.cc.s
.PHONY : ExtraPhysics.s

# target to generate assembly for a file
ExtraPhysics.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/ExtraPhysics.cc.s
.PHONY : ExtraPhysics.cc.s

G4HodoscopeDetectorConstruction.o: G4HodoscopeDetectorConstruction.cc.o
.PHONY : G4HodoscopeDetectorConstruction.o

# target to build an object file
G4HodoscopeDetectorConstruction.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeDetectorConstruction.cc.o
.PHONY : G4HodoscopeDetectorConstruction.cc.o

G4HodoscopeDetectorConstruction.i: G4HodoscopeDetectorConstruction.cc.i
.PHONY : G4HodoscopeDetectorConstruction.i

# target to preprocess a source file
G4HodoscopeDetectorConstruction.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeDetectorConstruction.cc.i
.PHONY : G4HodoscopeDetectorConstruction.cc.i

G4HodoscopeDetectorConstruction.s: G4HodoscopeDetectorConstruction.cc.s
.PHONY : G4HodoscopeDetectorConstruction.s

# target to generate assembly for a file
G4HodoscopeDetectorConstruction.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeDetectorConstruction.cc.s
.PHONY : G4HodoscopeDetectorConstruction.cc.s

G4HodoscopeEventAction.o: G4HodoscopeEventAction.cc.o
.PHONY : G4HodoscopeEventAction.o

# target to build an object file
G4HodoscopeEventAction.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeEventAction.cc.o
.PHONY : G4HodoscopeEventAction.cc.o

G4HodoscopeEventAction.i: G4HodoscopeEventAction.cc.i
.PHONY : G4HodoscopeEventAction.i

# target to preprocess a source file
G4HodoscopeEventAction.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeEventAction.cc.i
.PHONY : G4HodoscopeEventAction.cc.i

G4HodoscopeEventAction.s: G4HodoscopeEventAction.cc.s
.PHONY : G4HodoscopeEventAction.s

# target to generate assembly for a file
G4HodoscopeEventAction.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeEventAction.cc.s
.PHONY : G4HodoscopeEventAction.cc.s

G4HodoscopePhysicsList.o: G4HodoscopePhysicsList.cc.o
.PHONY : G4HodoscopePhysicsList.o

# target to build an object file
G4HodoscopePhysicsList.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopePhysicsList.cc.o
.PHONY : G4HodoscopePhysicsList.cc.o

G4HodoscopePhysicsList.i: G4HodoscopePhysicsList.cc.i
.PHONY : G4HodoscopePhysicsList.i

# target to preprocess a source file
G4HodoscopePhysicsList.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopePhysicsList.cc.i
.PHONY : G4HodoscopePhysicsList.cc.i

G4HodoscopePhysicsList.s: G4HodoscopePhysicsList.cc.s
.PHONY : G4HodoscopePhysicsList.s

# target to generate assembly for a file
G4HodoscopePhysicsList.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopePhysicsList.cc.s
.PHONY : G4HodoscopePhysicsList.cc.s

G4HodoscopeRunAction.o: G4HodoscopeRunAction.cc.o
.PHONY : G4HodoscopeRunAction.o

# target to build an object file
G4HodoscopeRunAction.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeRunAction.cc.o
.PHONY : G4HodoscopeRunAction.cc.o

G4HodoscopeRunAction.i: G4HodoscopeRunAction.cc.i
.PHONY : G4HodoscopeRunAction.i

# target to preprocess a source file
G4HodoscopeRunAction.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeRunAction.cc.i
.PHONY : G4HodoscopeRunAction.cc.i

G4HodoscopeRunAction.s: G4HodoscopeRunAction.cc.s
.PHONY : G4HodoscopeRunAction.s

# target to generate assembly for a file
G4HodoscopeRunAction.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeRunAction.cc.s
.PHONY : G4HodoscopeRunAction.cc.s

G4HodoscopeSimulator.o: G4HodoscopeSimulator.cc.o
.PHONY : G4HodoscopeSimulator.o

# target to build an object file
G4HodoscopeSimulator.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSimulator.cc.o
.PHONY : G4HodoscopeSimulator.cc.o

G4HodoscopeSimulator.i: G4HodoscopeSimulator.cc.i
.PHONY : G4HodoscopeSimulator.i

# target to preprocess a source file
G4HodoscopeSimulator.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSimulator.cc.i
.PHONY : G4HodoscopeSimulator.cc.i

G4HodoscopeSimulator.s: G4HodoscopeSimulator.cc.s
.PHONY : G4HodoscopeSimulator.s

# target to generate assembly for a file
G4HodoscopeSimulator.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSimulator.cc.s
.PHONY : G4HodoscopeSimulator.cc.s

G4HodoscopeSteppingAction.o: G4HodoscopeSteppingAction.cc.o
.PHONY : G4HodoscopeSteppingAction.o

# target to build an object file
G4HodoscopeSteppingAction.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSteppingAction.cc.o
.PHONY : G4HodoscopeSteppingAction.cc.o

G4HodoscopeSteppingAction.i: G4HodoscopeSteppingAction.cc.i
.PHONY : G4HodoscopeSteppingAction.i

# target to preprocess a source file
G4HodoscopeSteppingAction.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSteppingAction.cc.i
.PHONY : G4HodoscopeSteppingAction.cc.i

G4HodoscopeSteppingAction.s: G4HodoscopeSteppingAction.cc.s
.PHONY : G4HodoscopeSteppingAction.s

# target to generate assembly for a file
G4HodoscopeSteppingAction.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeSteppingAction.cc.s
.PHONY : G4HodoscopeSteppingAction.cc.s

G4HodoscopeTrackingAction.o: G4HodoscopeTrackingAction.cc.o
.PHONY : G4HodoscopeTrackingAction.o

# target to build an object file
G4HodoscopeTrackingAction.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeTrackingAction.cc.o
.PHONY : G4HodoscopeTrackingAction.cc.o

G4HodoscopeTrackingAction.i: G4HodoscopeTrackingAction.cc.i
.PHONY : G4HodoscopeTrackingAction.i

# target to preprocess a source file
G4HodoscopeTrackingAction.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeTrackingAction.cc.i
.PHONY : G4HodoscopeTrackingAction.cc.i

G4HodoscopeTrackingAction.s: G4HodoscopeTrackingAction.cc.s
.PHONY : G4HodoscopeTrackingAction.s

# target to generate assembly for a file
G4HodoscopeTrackingAction.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/G4HodoscopeTrackingAction.cc.s
.PHONY : G4HodoscopeTrackingAction.cc.s

OpticalPhysics.o: OpticalPhysics.cc.o
.PHONY : OpticalPhysics.o

# target to build an object file
OpticalPhysics.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/OpticalPhysics.cc.o
.PHONY : OpticalPhysics.cc.o

OpticalPhysics.i: OpticalPhysics.cc.i
.PHONY : OpticalPhysics.i

# target to preprocess a source file
OpticalPhysics.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/OpticalPhysics.cc.i
.PHONY : OpticalPhysics.cc.i

OpticalPhysics.s: OpticalPhysics.cc.s
.PHONY : OpticalPhysics.s

# target to generate assembly for a file
OpticalPhysics.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/OpticalPhysics.cc.s
.PHONY : OpticalPhysics.cc.s

StepMax.o: StepMax.cc.o
.PHONY : StepMax.o

# target to build an object file
StepMax.cc.o:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/StepMax.cc.o
.PHONY : StepMax.cc.o

StepMax.i: StepMax.cc.i
.PHONY : StepMax.i

# target to preprocess a source file
StepMax.cc.i:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/StepMax.cc.i
.PHONY : StepMax.cc.i

StepMax.s: StepMax.cc.s
.PHONY : StepMax.s

# target to generate assembly for a file
StepMax.cc.s:
	cd /opt/meiga/build && $(MAKE) $(MAKESILENT) -f Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/build.make Applications/G4HodoscopeSimulator/CMakeFiles/G4HodoscopeSimulator.dir/StepMax.cc.s
.PHONY : StepMax.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... G4HodoscopeSimulator"
	@echo "... ExtraPhysics.o"
	@echo "... ExtraPhysics.i"
	@echo "... ExtraPhysics.s"
	@echo "... G4HodoscopeDetectorConstruction.o"
	@echo "... G4HodoscopeDetectorConstruction.i"
	@echo "... G4HodoscopeDetectorConstruction.s"
	@echo "... G4HodoscopeEventAction.o"
	@echo "... G4HodoscopeEventAction.i"
	@echo "... G4HodoscopeEventAction.s"
	@echo "... G4HodoscopePhysicsList.o"
	@echo "... G4HodoscopePhysicsList.i"
	@echo "... G4HodoscopePhysicsList.s"
	@echo "... G4HodoscopeRunAction.o"
	@echo "... G4HodoscopeRunAction.i"
	@echo "... G4HodoscopeRunAction.s"
	@echo "... G4HodoscopeSimulator.o"
	@echo "... G4HodoscopeSimulator.i"
	@echo "... G4HodoscopeSimulator.s"
	@echo "... G4HodoscopeSteppingAction.o"
	@echo "... G4HodoscopeSteppingAction.i"
	@echo "... G4HodoscopeSteppingAction.s"
	@echo "... G4HodoscopeTrackingAction.o"
	@echo "... G4HodoscopeTrackingAction.i"
	@echo "... G4HodoscopeTrackingAction.s"
	@echo "... OpticalPhysics.o"
	@echo "... OpticalPhysics.i"
	@echo "... OpticalPhysics.s"
	@echo "... StepMax.o"
	@echo "... StepMax.i"
	@echo "... StepMax.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /opt/meiga/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

